### ISSUE TITLE
Invalid_payment_type_code

### ISSUE THREAD

**Issue by sopedro** [ebanx/magento-gateway-ebanx#147]
On credit card payment for Brazil i get this error. Note: I have credit card for Brazil active.
Other issue is that the IOF is not well calculated for eg. for a total amount of R$128 it show a message "Total to be Paid with IOF(0.38%) R$506". This is weird.

**Comment by SparK-Cruz** [comment]
Hello, sorry for the delay.

Those issues are fixed :) all the fixes that were in develop branch just got tagged 2.1.0 in master so it shouldn't display that behaviour anymore.

If you need anything just yell for help.
