### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sopedro** [ebanx/magento-gateway-ebanx#186]
this is calling a missing file require_once Mage::getBaseDir('lib') . '/Ebanx/vendor/autoload.php';
This file is missing too app/code/community/Ebanx/Gateway/Model/Api.php on line 2
and so on, i have to uninstall the extension.

**Comment by gpressutto5** [comment]
Hello sopedro! Thank you for your feedback!
Did you download our zip from [github releases page](https://github.com/ebanx/magento-gateway-ebanx/releases)? If you did this is really an error.
If you've cloned our repository you need to run `composer install`. It will download the latest version of our [PHP lib](https://github.com/ebanx/benjamin) and generate the autoload.

**Comment by SparK-Cruz** [comment]
@sopedro Have you managed to download the composer dependencies or use the release zip?
If se tell us so we can close the issue =D

**Comment by sopedro** [comment]
Hi @SparK-Cruz . I download de zip release.
