### ISSUE TITLE
Static function Ebanx_Gateway_Log_Logger::persist() should not be abstract

### ISSUE THREAD

**Issue by r-martins** [ebanx/magento-gateway-ebanx#318]
O erro ocorre ao salvar as configurações de pagamento.

![configuration___system___administracao_magento](https://user-images.githubusercontent.com/191149/43872674-23293870-9bc6-11e8-8dc7-1b330dd5a804.jpg)

PHP 5.6.32
Ambiente local (Developer Mode On)

**Comment by andercampanha** [comment]
We will be taking care of this shortly. Thanks for the heads up.
