### ISSUE TITLE
Mascara sendo aplicada mesmo com a config marcada para não

### ISSUE THREAD

**Issue by r-martins** [ebanx/magento-gateway-ebanx#319]
A máscara de CPF é aplicada no campo Taxvat no front end mesmo que a opção esteja como não.
![configuration___system___administracao_magento](https://user-images.githubusercontent.com/191149/43873305-8a0f734e-9bc9-11e8-893f-07360e9f88ac.jpg)

![fechar_pedido_and_magenteiro____www_magenteiro__-_____skin_frontend_base_default_ebanx_js_input-handler_js__aprendamagento_](https://user-images.githubusercontent.com/191149/43873338-9e4514e0-9bc9-11e8-9512-16ec13b1459d.jpg)

**Comment by r-martins** [comment]
Possível solução:

> <action method="addItem" ifconfig="payment/ebanx_settings/mask_taxvat_field">
>                 <type>skin_js</type>
>                 <script>ebanx/js/input-handler.js</script>
>             </action>
em app/design/frontend/base/default/layout/ebanx.xml

**Comment by andercampanha** [comment]
We will be taking care of it shortly. Thanks for the tip.
