### ISSUE TITLE
Refunds

### ISSUE THREAD

**Issue by cezarlz** [ebanx/magento-gateway-ebanx#4]
The merchant can create refunds via magento admin panel.

Refunds rules:
- Only on orders created by EBANX gateways can be refunded
- The amount must be greater than $1
- The merchant can view the created refunds

**Comment by rvelhote** [comment]
Hey @cezarlz ,

Do you have a beta version or a branch of this feature? We are looking to have this in our project and we would like to help test this feature.

Best regards,
Ricardo

**Comment by SparK-Cruz** [comment]
Hey @rvelhote, sorry for the delay (wow, almost four months).
We had a focus shift in our team with two more members working on our plugins (me included), so we will deliver the full feature set soon.
Also Cezar is in germany.

If you have any suggestions on how it should be implemented, and other feature requests, don't be shy to open an issue.
